options(scipen = 999)
library(dplyr) # 
library(lubridate) 
library(tidyverse)  
library(zoo)  
library(here) #
library(openintro)
library(readxl) 
library(readr) 
library(fst) 
library(rlang) 
library(sf) 
library(data.table)
library(tidyr)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(classInt)
library(MetBrewer)
library(splines)
library(purrr) 
library(survival)
library(hrbrthemes)
library(data.table)
library(patchwork)
library(rstatix)
library(grid)
library(webshot)
library(stringi)
library(stringr) 
library(areal)
library(explore)